source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ARProject00' do
       pod 'LocationKit', '~> 3.0'
       pod 'SwiftyBeaver'
end


workspace 'ARProject00'

